//! Conservative passphrase checks that avoid false entropy claims.

use std::collections::BTreeSet;

use bip39::{Language, Mnemonic};
use serde::Serialize;
use unicode_normalization::UnicodeNormalization;

/// A conservative, offline assessment of a passphrase.
#[derive(Debug, Clone, Eq, PartialEq, Serialize)]
pub struct PassphraseAudit {
    /// Unicode scalar count after BIP39 NFKD normalization.
    pub normalized_character_count: usize,
    /// Number of word-like tokens split on whitespace and hyphens.
    pub token_count: usize,
    /// Whether BIP39 NFKD normalization changes the input.
    pub normalization_changes_input: bool,
    /// Whether any token is repeated.
    pub has_repeated_tokens: bool,
    /// Whether the input itself is a valid English BIP39 mnemonic.
    pub resembles_bip39_mnemonic: bool,
    /// Human-readable warnings; an empty list is not a proof of strength.
    pub warnings: Vec<String>,
    /// Construction entropy, populated only for passphrases generated by this tool.
    pub verified_construction_entropy_bits: Option<usize>,
}

impl PassphraseAudit {
    /// Return true when no obvious weakness indicator was found.
    ///
    /// This is intentionally not named `is_strong`: absence of these indicators
    /// does not prove resistance to guessing.
    #[must_use]
    pub fn has_no_obvious_warning(&self) -> bool {
        self.warnings.is_empty()
    }
}

/// Audit a passphrase without assigning entropy to human choice.
#[must_use]
pub fn audit_passphrase(input: &str) -> PassphraseAudit {
    audit_passphrase_with_entropy(input, None)
}

/// Audit a passphrase with trusted construction entropy from a known generator.
#[must_use]
pub fn audit_passphrase_with_entropy(
    input: &str,
    verified_construction_entropy_bits: Option<usize>,
) -> PassphraseAudit {
    let normalized = zeroize::Zeroizing::new(input.nfkd().collect::<String>());
    let tokens: Vec<&str> = normalized
        .split(|character: char| character.is_whitespace() || character == '-')
        .filter(|token| !token.is_empty())
        .collect();
    let unique: BTreeSet<&str> = tokens.iter().copied().collect();
    let has_repeated_tokens = unique.len() != tokens.len();
    let resembles_bip39_mnemonic =
        Mnemonic::parse_in_normalized(Language::English, normalized.as_str()).is_ok();
    let normalized_character_count = normalized.chars().count();
    let mut warnings = Vec::new();

    if normalized.is_empty() {
        warnings.push("Empty passphrase: the protected wallet equals the base wallet.".to_owned());
    }
    if verified_construction_entropy_bits.is_none() {
        warnings.push(
            "Human-chosen passphrases have unknown entropy; length alone is not proof of strength."
                .to_owned(),
        );
    }
    if verified_construction_entropy_bits.is_some_and(|bits| bits < 128) {
        warnings.push(
            "Generated construction entropy is below the 128-bit target; this buys time but does not meet the default target."
                .to_owned(),
        );
    }
    if normalized_character_count < 20 {
        warnings.push("Fewer than 20 normalized characters is a high-risk choice.".to_owned());
    }
    if tokens.len() < 6 {
        warnings.push("Fewer than 6 word-like tokens is easier to guess.".to_owned());
    }
    if has_repeated_tokens {
        warnings.push("Repeated tokens reduce the effective search space.".to_owned());
    }
    if resembles_bip39_mnemonic {
        warnings.push(
            "The passphrase is itself a valid BIP39 mnemonic; never reuse wallet seed words as a passphrase."
                .to_owned(),
        );
    }
    if normalized
        .chars()
        .all(|character| character.is_ascii_digit())
        && !normalized.is_empty()
    {
        warnings.push("Digits-only passphrases are vulnerable to targeted search.".to_owned());
    }

    PassphraseAudit {
        normalized_character_count,
        token_count: tokens.len(),
        normalization_changes_input: normalized.as_str() != input,
        has_repeated_tokens,
        resembles_bip39_mnemonic,
        warnings,
        verified_construction_entropy_bits,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn human_input_never_gets_invented_entropy() {
        let audit = audit_passphrase("correct horse battery staple");
        assert_eq!(audit.verified_construction_entropy_bits, None);
        assert!(
            audit
                .warnings
                .iter()
                .any(|warning| warning.contains("unknown entropy"))
        );
    }

    #[test]
    fn empty_passphrase_is_flagged() {
        let audit = audit_passphrase("");
        assert!(
            audit
                .warnings
                .iter()
                .any(|warning| warning.contains("equals the base"))
        );
    }

    #[test]
    fn seed_reuse_shape_is_flagged() {
        let audit = audit_passphrase(
            "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about",
        );
        assert!(audit.resembles_bip39_mnemonic);
    }

    #[test]
    fn generated_entropy_below_target_is_flagged() {
        let audit =
            audit_passphrase_with_entropy("abandon-ability-able-about-above-absent", Some(66));
        assert!(
            audit
                .warnings
                .iter()
                .any(|warning| warning.contains("below the 128-bit target"))
        );
    }
}
